sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install pytest pytest-cov

script:
  - coverage run tests/test_main.py
  - pytest --cov=./

after_success:
  - codecov
